### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Foen100** [MarkoPaul0/DatagramTunneler#6]
Hello,
when i run make, this error appears: 
mkdir -p bin/ build/
g++ -std=c++11 -Wall -Wconversion -Wsign-compare -Wreorder -Wold-style-cast -Werror  -o build//DatagramTunneler.o -c src/DatagramTunneler.cpp #src/main.cpp
src/DatagramTunneler.cpp:13:10: fatal error: Log.h: Datei oder Verzeichnis nicht gefunden
 #include "Log.h"
          ^~~~~~~
compilation terminated.
make: *** [makefile:14: build/DatagramTunneler.o] Fehler 1

Hope you can help me with that. Thank you.
Tobi

**Comment by MarkoPaul0** [comment]
I believe I have fixed the issue. There was a problem with how the git repo was setup. I had recently renamed a file from log.h to Log.h. The change was preserved but not detected. Please pull the latest and try to build again. Let me know if that resolves the issue.

**Comment by MarkoPaul0** [comment]
Closing the issue. I believe it is fixed. Please reopen if needed.

**Comment by Foen100** [comment]
I'm sorry I didn't get in touch. Unfortunately, there is still an error:

root@server:/home/baaum/DatagramTunneler-master# make
mkdir -p bin/ build/
g++ -std=c++11 -Wall -Wconversion -Wsign-compare -Wreorder -Wold-style-cast -Werror  -o build//DatagramTunneler.o -c src/DatagramTunneler.cpp #src/main.cpp
g++ -std=c++11 -Wall -Wconversion -Wsign-compare -Wreorder -Wold-style-cast -Werror  -o build/main.o -c src/main.cpp
src/main.cpp: In function ‘uint16_t getPort(const string&)’:
src/main.cpp:16:18: error: ‘invalid_argument’ in namespace ‘std’ does not name a type
     } catch(std::invalid_argument& ex) {
                  ^~~~~~~~~~~~~~~~
src/main.cpp: In function ‘bool getCommandLineConfig(int, char**, DatagramTunneler::Config*)’:
src/main.cpp:88:13: error: ‘assert’ was not declared in this scope
             assert(side_selected);
             ^~~~~~
src/main.cpp:88:13: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
src/main.cpp:7:1:
+#include <cassert>

src/main.cpp:88:13:
             assert(side_selected);
             ^~~~~~
make: *** [makefile:11: build/main.o] Fehler 1




Thank you for your help

**Comment by MarkoPaul0** [comment]
Very interesting that it even compiles on my side since there definitely are some missing includes. I added them on my setup, but since it compiled before I cannot tell if I fixed everything. To verify further I'd have to compile on a linux box which I don't have handy right now.
Please pull the latest and try once more to see if that fixes it.

**Comment by Foen100** [comment]
Thank you very much. Now it is working. One more question. Is it possible to run it with ngrok. So that the client do not have to install DatagramTunneler? For exmaple you use this tcp port "tcp://0.tcp.ngrok.io:18258" also for udp.
Thank you
